[general]
import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[window]
decorations = "None"

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
size = 16

